export const Users = [
    {
      _id:1,
      profilePic: "person/hancock.webp",
      username: "Safak Kocaoglu",
    },
    {
      _id:2,
      profilePic: "person/hancock.webp",
      username: "Janell Shrum",
    },
    {
      _id:3,
      profilePic: "person/hancock.webp",
      username: "Alex Durden",
    },
    {
      _id:4,
      profilePic: "person/hancock.webp",
      username: "Dora Hawks",
    },
    {
      _id:5,
      profilePic: "person/robin.jpg",
      username: "Thomas Holden",
    },
    {
      _id:6,
      profilePic: "person/robin.jpg",
      username: "Shirley Beauchamp",
    },
    {
      _id:7,
      profilePic: "person/robin.jpg",
      username: "Travis Bennett",
    },
    {
      _id:8,
      profilePic: "person/robin.jpg",
      username: "Kristen Thomas",
    },
    {
      _id:9,
      profilePic: "person/Yamato.webp",
      username: "Gary Duty",
    },
    {
      _id:10,
      profilePic: "person/Yamato.webp",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      _id: 1,
      desc: "Love For All, Hatred For None.",
      img: "post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      _id: 2,
      img: "post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      _id: 3,
      desc: "Every moment is a fresh beginning.",
      img: "post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      _id: 4,
      img: "post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      _id: 5,
      img: "post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      _id: 6,
      img: "post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      _id: 7,
      desc: "Never regret anything that made you smile.",
      img: "post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      _id: 8,
      img: "post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      _id: 9,
      desc: "Change the world by being yourself.",
      img: "post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      _id: 10,
      img: "post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];